services:
  - type: web
    name: smartlearn-php
    env: docker
    repo: https://github.com/Kiluhub/freelance-php
    region: oregon
    branch: main
    plan: free

    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
