services:
  - type: web
    name: smartlearn-web
    env: php
    plan: free
    buildCommand: ""  # no build step for PHP
    startCommand: ""  # Apache auto-starts for PHP
    rootDir: applic   # 👈 This tells Render to serve from the 'applic/' folder
    autoDeploy: true
    region: oregon

databases:
  - name: smartlearn-db
    databaseName: smartlearn_iaqb
    user: smartlearn_iaqb_user
    plan: free
    region: oregon
