services:
  - type: web
    name: smartlearn-web
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    region: oregon

databases:
  - name: smartlearn-db
    databaseName: smartlearn_iaqb
    user: smartlearn_iaqb_user
    plan: free
    region: oregon
